version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST= "devops-exam-db.cvu4cuyqyi5s.ap-south-1.rds.amazonaws.com"
      - DB_USER= "admin" 
      - DB_PASSWORD= "admin123"
      - DB_NAME= "devops-exam-db"
      - SESSION_SECRET=devops-exam-secret

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exam_db
      MYSQL_USER: exam_user
      MYSQL_PASSWORD: exam_password
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
